/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DenunciarRouteImport } from './routes/denunciar'
import { Route as LineasRouteImport } from './routes/lineas'
import { Route as SenalesRouteImport } from './routes/senales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DenunciarRoute = DenunciarRouteImport.update({
  id: '/denunciar',
  path: '/denunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const LineasRoute = LineasRouteImport.update({
  id: '/lineas',
  path: '/lineas',
  getParentRoute: () => rootRouteImport,
} as any)
const SenalesRoute = SenalesRouteImport.update({
  id: '/senales',
  path: '/senales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denunciar': typeof DenunciarRoute
  '/lineas': typeof LineasRoute
  '/senales': typeof SenalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denunciar': typeof DenunciarRoute
  '/lineas': typeof LineasRoute
  '/senales': typeof SenalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/denunciar': typeof DenunciarRoute
  '/lineas': typeof LineasRoute
  '/senales': typeof SenalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/denunciar' | '/lineas' | '/senales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/denunciar' | '/lineas' | '/senales'
  id: '__root__' | '/' | '/denunciar' | '/lineas' | '/senales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenunciarRoute: typeof DenunciarRoute
  LineasRoute: typeof LineasRoute
  SenalesRoute: typeof SenalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denunciar': {
      id: '/denunciar'
      path: '/denunciar'
      fullPath: '/denunciar'
      preLoaderRoute: typeof DenunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineas': {
      id: '/lineas'
      path: '/lineas'
      fullPath: '/lineas'
      preLoaderRoute: typeof LineasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senales': {
      id: '/senales'
      path: '/senales'
      fullPath: '/senales'
      preLoaderRoute: typeof SenalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenunciarRoute: DenunciarRoute,
  LineasRoute: LineasRoute,
  SenalesRoute: SenalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
